# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a9d31ca348313e5f35e77402cd140f8b0bd08f70a33162d54e81e218ddf42051ed5e2dc6f5984140a615073278788392cff1761e08e44c15ed0f1a4e6d8ca359

test:
  secret_key_base: 5edc8009a97547575d1d5c20a5641611334a734bc042305f5807b4be5b1724af13c8a6a94bc389eb2d89832d594c210d7b685ba66aa89a13eeaee8e33f159a3d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
